### ISSUE TITLE
[Bug] Purescript Build Failing

### ISSUE THREAD

**Issue by tws4793** [smucclaw/vue-pure-pdpa#53]
## Expected Behaviour
Run `npx spago install` to install purescript packages without errors. This should also work when we `npm run serve`, as the purescript needs to be compiled first before the application can be run in development mode.

## Actual Behaviour
Build failing with the following error message:

```
[error] Oh noes! It looks like the PureScript version installed on your system is not compatible with the package-set you're using.

installed `purs` version:    0.15.2
minimum package-set version: 0.14.3

There are a few ways to solve this:
- install a compatible `purs` version (i.e. in the same 'semver range' as the one in the package set)
- if the `purs` version is 'too new', you can try using `spago upgrade-set` to upgrade to the latest package set
- if you know what you're doing and you want to disable this check, you can override the `version` of the `metadata` package in the packages.dhall, e.g.:

  let upstream = <package-set url here>
  in  upstream
    with metadata.version = "v0.15.2"
```

Also affects the **Node.js CI** Github workflow.

## Environment
- Node v16.13.0
- npm v8.1.0
- purs v0.15.2
- spago v0.20.9

## To Reproduce Error
- Run `npx spago install`

**Comment by tws4793** [comment]
When attempting to `npm run serve`, it produces the following error:

```
Failed to compile.

./src/AnyAll.purs
Module build failed (from ./node_modules/purs-loader/lib/index.js):
Error: compilation failed: [  1 of 341] Compiling Unsafe.Coerce
[  2 of 341] Compiling Record.Unsafe
[  3 of 341] Compiling Foreign.Internal.Stringify
[  4 of 341] Compiling Math
[  5 of 341] Compiling Partial
[  7 of 341] Compiling Data.Int.Bits
[  6 of 341] Compiling Data.Symbol
[  8 of 341] Compiling Data.String.Unsafe

    at ChildProcess.<anonymous> (/Users/tws/Developer/fe/node_modules/purs-loader/lib/compile.js:53:18)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1090:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:527:28)
    at Pipe.<anonymous> (node:net:715:12)
From previous event:
    at compile (/Users/tws/Developer/fe/node_modules/purs-loader/lib/compile.js:29:10)
    at Object.purescriptLoader (/Users/tws/Developer/fe/node_modules/purs-loader/lib/index.js:335:7)
```

**Comment by tws4793** [comment]
The fix was simply:

```console
$ npm install --save-dev purescript@0.14.3
```

The `package.json` will indicate the version as `^0.14.3`.

The `^` in front of the version number on the command is optional, by which then the `package.json` will indicate as `^0.14.9`.
